### ISSUE TITLE
Listing pods not working

### ISSUE THREAD

**Issue by pradeepcheers** [hnaderi/scala-k8s#94]
Tried to list the pods like below but it doesn't seem to work.

`buildClient.use(APIs.pods.list().send).map(println)`

I could list the pods using the curl command!

`curl -s http://localhost:8080/api/v1/namespaces/default/pods/ | jq -rM '.items[].metadata.name'`

**Comment by hnaderi** [comment]
Hi
The API calls you have shared are not the same, 
`APIs.pods.list()` is the cluster wide resource `api/v1/pods`.
If you want to list pods from default namespace you need to use:
`APIs.namespace("default").pods`

**Comment by davesmith00sky** [comment]
Hi @hnaderi,

@pradeepcheers has been pulled onto something else so I thought I'd follow up. Thanks for getting back to us.

We're trying out a couple of k8s clients and we're struggling to get this one to work as expected (yours was our first choice! 😄), particularly in the case of listing pods. Listing resources other than pods seems to work ok.

What may not have been clear from the original report was that, the problem isn't that we're not seeing the results we expect, it's that we're getting decoding errors.

Http4s:
```
[error] org.http4s.InvalidMessageBodyFailure: Invalid message body: DecodingFailure at : Got value 'null' with wrong type, expecting string
[error] 	at org.http4s.InvalidMessageBodyFailure$.apply(MessageFailure.scala:118)
[error] 	at dev.hnaderi.k8s.client.Http4sKubernetesClient.decoder$$anonfun$1$
```

Sttp:
```
Caused by: dev.hnaderi.k8s.client.SttpKubernetesClient$DecodeError: DecodingFailure at : Got value 'null' with wrong type, expecting string
	at dev.hnaderi.k8s.client.SttpKubernetesClient$DecodeError$.apply(SttpKubernetesClient.scala:118)
```

Clearly these are in fact the same Circe error, but we are making (we believe) the same API call with a different k8s Scala lib, and it succeeds.

Here is what we were doing last, though please note that we've tried as many permutations as we could think of, and they all failed in the same way - I even tried looking up a pod in the default names space by name at one point.

```scala
client.use(APIs.namespace("default").pods.list.send)
```

It's entirely probably that we've just messed up 😅, but I found the error surprising and opaque in terms of giving us any clue as to where we might have gone wrong.

More details: We're hitting a simple local minikube running two instances of nginx through a kubectl proxy, and we're just querying stuff and printing out the results to the terminal to see what we can see - nothing clever at all. The program is just a quick command line app not much bigger than your example one, run from sbt using Scala 3, but I did also try dropping to Scala 2 and saw the same issue.

Any ideas?

**Comment by davesmith00sky** [comment]
Kubernetes v1.26.1
scala-k8s 0.9.0

So I don't have a curl response showing the problem because I don't know what the problem is, but the equivalent JSON output (maybe this is what you meant?) to the call above is below (sorry it's very large...):

`curl -s http://localhost:8080/api/v1/namespaces/default/pods/ | jq`

```json
{
  "kind": "PodList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "207431"
  },
  "items": [
    {
      "metadata": {
        "name": "nginx-deployment-68d9b6c666-5jv96",
        "generateName": "nginx-deployment-68d9b6c666-",
        "namespace": "default",
        "uid": "e8173bc3-399b-4120-81f4-d81766c70d70",
        "resourceVersion": "207104",
        "creationTimestamp": "2023-03-01T16:40:56Z",
        "labels": {
          "app": "nginx",
          "pod-template-hash": "68d9b6c666"
        },
        "ownerReferences": [
          {
            "apiVersion": "apps/v1",
            "kind": "ReplicaSet",
            "name": "nginx-deployment-68d9b6c666",
            "uid": "9a797037-a458-4b96-b8eb-fa75680e0682",
            "controller": true,
            "blockOwnerDeletion": true
          }
        ],
        "managedFields": [
          {
            "manager": "kube-controller-manager",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2023-03-01T16:40:56Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:metadata": {
                "f:generateName": {},
                "f:labels": {
                  ".": {},
                  "f:app": {},
                  "f:pod-template-hash": {}
                },
                "f:ownerReferences": {
                  ".": {},
                  "k:{\"uid\":\"9a797037-a458-4b96-b8eb-fa75680e0682\"}": {}
                }
              },
              "f:spec": {
                "f:containers": {
                  "k:{\"name\":\"nginx\"}": {
                    ".": {},
                    "f:image": {},
                    "f:imagePullPolicy": {},
                    "f:name": {},
                    "f:ports": {
                      ".": {},
                      "k:{\"containerPort\":80,\"protocol\":\"TCP\"}": {
                        ".": {},
                        "f:containerPort": {},
                        "f:protocol": {}
                      }
                    },
                    "f:resources": {},
                    "f:terminationMessagePath": {},
                    "f:terminationMessagePolicy": {}
                  }
                },
                "f:dnsPolicy": {},
                "f:enableServiceLinks": {},
                "f:restartPolicy": {},
                "f:schedulerName": {},
                "f:securityContext": {},
                "f:terminationGracePeriodSeconds": {}
              }
            }
          },
          {
            "manager": "kubelet",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2023-04-20T16:52:29Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:status": {
                "f:conditions": {
                  "k:{\"type\":\"ContainersReady\"}": {
                    ".": {},
                    "f:lastProbeTime": {},
                    "f:lastTransitionTime": {},
                    "f:status": {},
                    "f:type": {}
                  },
                  "k:{\"type\":\"Initialized\"}": {
                    ".": {},
                    "f:lastProbeTime": {},
                    "f:lastTransitionTime": {},
                    "f:status": {},
                    "f:type": {}
                  },
                  "k:{\"type\":\"Ready\"}": {
                    ".": {},
                    "f:lastProbeTime": {},
                    "f:lastTransitionTime": {},
                    "f:status": {},
                    "f:type": {}
                  }
                },
                "f:containerStatuses": {},
                "f:hostIP": {},
                "f:phase": {},
                "f:podIP": {},
                "f:podIPs": {
                  ".": {},
                  "k:{\"ip\":\"10.244.0.14\"}": {
                    ".": {},
                    "f:ip": {}
                  }
                },
                "f:startTime": {}
              }
            },
            "subresource": "status"
          }
        ]
      },
      "spec": {
        "volumes": [
          {
            "name": "kube-api-access-g8nwj",
            "projected": {
              "sources": [
                {
                  "serviceAccountToken": {
                    "expirationSeconds": 3607,
                    "path": "token"
                  }
                },
                {
                  "configMap": {
                    "name": "kube-root-ca.crt",
                    "items": [
                      {
                        "key": "ca.crt",
                        "path": "ca.crt"
                      }
                    ]
                  }
                },
                {
                  "downwardAPI": {
                    "items": [
                      {
                        "path": "namespace",
                        "fieldRef": {
                          "apiVersion": "v1",
                          "fieldPath": "metadata.namespace"
                        }
                      }
                    ]
                  }
                }
              ],
              "defaultMode": 420
            }
          }
        ],
        "containers": [
          {
            "name": "nginx",
            "image": "nginx:1.16",
            "ports": [
              {
                "containerPort": 80,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "kube-api-access-g8nwj",
                "readOnly": true,
                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "default",
        "serviceAccount": "default",
        "nodeName": "minikube",
        "securityContext": {},
        "schedulerName": "default-scheduler",
        "tolerations": [
          {
            "key": "node.kubernetes.io/not-ready",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 300
          },
          {
            "key": "node.kubernetes.io/unreachable",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 300
          }
        ],
        "priority": 0,
        "enableServiceLinks": true,
        "preemptionPolicy": "PreemptLowerPriority"
      },
      "status": {
        "phase": "Running",
        "conditions": [
          {
            "type": "Initialized",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-03-01T16:40:56Z"
          },
          {
            "type": "Ready",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-04-20T16:52:26Z"
          },
          {
            "type": "ContainersReady",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-04-20T16:52:26Z"
          },
          {
            "type": "PodScheduled",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-03-01T16:40:56Z"
          }
        ],
        "hostIP": "192.168.49.2",
        "podIP": "10.244.0.14",
        "podIPs": [
          {
            "ip": "10.244.0.14"
          }
        ],
        "startTime": "2023-03-01T16:40:56Z",
        "containerStatuses": [
          {
            "name": "nginx",
            "state": {
              "running": {
                "startedAt": "2023-04-20T16:52:25Z"
              }
            },
            "lastState": {
              "terminated": {
                "exitCode": 0,
                "reason": "Completed",
                "startedAt": "2023-04-20T09:03:51Z",
                "finishedAt": "2023-04-20T16:40:51Z",
                "containerID": "docker://71057d2d4f4eb9faa937532e3eb4982b8edc6f6ac078e86af9e59cae0a6d1e84"
              }
            },
            "ready": true,
            "restartCount": 3,
            "image": "nginx:1.16",
            "imageID": "docker-pullable://nginx@sha256:d20aa6d1cae56fd17cd458f4807e0de462caf2336f0b70b5eeb69fcaaf30dd9c",
            "containerID": "docker://70a650901b950e3b69bd06873f296af6288e20e8d028ee891955b39647c7367b",
            "started": true
          }
        ],
        "qosClass": "BestEffort"
      }
    },
    {
      "metadata": {
        "name": "nginx-deployment-68d9b6c666-9fjsg",
        "generateName": "nginx-deployment-68d9b6c666-",
        "namespace": "default",
        "uid": "ca91c766-4eb3-42e5-9922-e9a53785e143",
        "resourceVersion": "207103",
        "creationTimestamp": "2023-03-01T16:40:20Z",
        "labels": {
          "app": "nginx",
          "pod-template-hash": "68d9b6c666"
        },
        "ownerReferences": [
          {
            "apiVersion": "apps/v1",
            "kind": "ReplicaSet",
            "name": "nginx-deployment-68d9b6c666",
            "uid": "9a797037-a458-4b96-b8eb-fa75680e0682",
            "controller": true,
            "blockOwnerDeletion": true
          }
        ],
        "managedFields": [
          {
            "manager": "kube-controller-manager",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2023-03-01T16:40:20Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:metadata": {
                "f:generateName": {},
                "f:labels": {
                  ".": {},
                  "f:app": {},
                  "f:pod-template-hash": {}
                },
                "f:ownerReferences": {
                  ".": {},
                  "k:{\"uid\":\"9a797037-a458-4b96-b8eb-fa75680e0682\"}": {}
                }
              },
              "f:spec": {
                "f:containers": {
                  "k:{\"name\":\"nginx\"}": {
                    ".": {},
                    "f:image": {},
                    "f:imagePullPolicy": {},
                    "f:name": {},
                    "f:ports": {
                      ".": {},
                      "k:{\"containerPort\":80,\"protocol\":\"TCP\"}": {
                        ".": {},
                        "f:containerPort": {},
                        "f:protocol": {}
                      }
                    },
                    "f:resources": {},
                    "f:terminationMessagePath": {},
                    "f:terminationMessagePolicy": {}
                  }
                },
                "f:dnsPolicy": {},
                "f:enableServiceLinks": {},
                "f:restartPolicy": {},
                "f:schedulerName": {},
                "f:securityContext": {},
                "f:terminationGracePeriodSeconds": {}
              }
            }
          },
          {
            "manager": "kubelet",
            "operation": "Update",
            "apiVersion": "v1",
            "time": "2023-04-20T16:52:29Z",
            "fieldsType": "FieldsV1",
            "fieldsV1": {
              "f:status": {
                "f:conditions": {
                  "k:{\"type\":\"ContainersReady\"}": {
                    ".": {},
                    "f:lastProbeTime": {},
                    "f:lastTransitionTime": {},
                    "f:status": {},
                    "f:type": {}
                  },
                  "k:{\"type\":\"Initialized\"}": {
                    ".": {},
                    "f:lastProbeTime": {},
                    "f:lastTransitionTime": {},
                    "f:status": {},
                    "f:type": {}
                  },
                  "k:{\"type\":\"Ready\"}": {
                    ".": {},
                    "f:lastProbeTime": {},
                    "f:lastTransitionTime": {},
                    "f:status": {},
                    "f:type": {}
                  }
                },
                "f:containerStatuses": {},
                "f:hostIP": {},
                "f:phase": {},
                "f:podIP": {},
                "f:podIPs": {
                  ".": {},
                  "k:{\"ip\":\"10.244.0.15\"}": {
                    ".": {},
                    "f:ip": {}
                  }
                },
                "f:startTime": {}
              }
            },
            "subresource": "status"
          }
        ]
      },
      "spec": {
        "volumes": [
          {
            "name": "kube-api-access-ll9nf",
            "projected": {
              "sources": [
                {
                  "serviceAccountToken": {
                    "expirationSeconds": 3607,
                    "path": "token"
                  }
                },
                {
                  "configMap": {
                    "name": "kube-root-ca.crt",
                    "items": [
                      {
                        "key": "ca.crt",
                        "path": "ca.crt"
                      }
                    ]
                  }
                },
                {
                  "downwardAPI": {
                    "items": [
                      {
                        "path": "namespace",
                        "fieldRef": {
                          "apiVersion": "v1",
                          "fieldPath": "metadata.namespace"
                        }
                      }
                    ]
                  }
                }
              ],
              "defaultMode": 420
            }
          }
        ],
        "containers": [
          {
            "name": "nginx",
            "image": "nginx:1.16",
            "ports": [
              {
                "containerPort": 80,
                "protocol": "TCP"
              }
            ],
            "resources": {},
            "volumeMounts": [
              {
                "name": "kube-api-access-ll9nf",
                "readOnly": true,
                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount"
              }
            ],
            "terminationMessagePath": "/dev/termination-log",
            "terminationMessagePolicy": "File",
            "imagePullPolicy": "IfNotPresent"
          }
        ],
        "restartPolicy": "Always",
        "terminationGracePeriodSeconds": 30,
        "dnsPolicy": "ClusterFirst",
        "serviceAccountName": "default",
        "serviceAccount": "default",
        "nodeName": "minikube",
        "securityContext": {},
        "schedulerName": "default-scheduler",
        "tolerations": [
          {
            "key": "node.kubernetes.io/not-ready",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 300
          },
          {
            "key": "node.kubernetes.io/unreachable",
            "operator": "Exists",
            "effect": "NoExecute",
            "tolerationSeconds": 300
          }
        ],
        "priority": 0,
        "enableServiceLinks": true,
        "preemptionPolicy": "PreemptLowerPriority"
      },
      "status": {
        "phase": "Running",
        "conditions": [
          {
            "type": "Initialized",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-03-01T16:40:20Z"
          },
          {
            "type": "Ready",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-04-20T16:52:26Z"
          },
          {
            "type": "ContainersReady",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-04-20T16:52:26Z"
          },
          {
            "type": "PodScheduled",
            "status": "True",
            "lastProbeTime": null,
            "lastTransitionTime": "2023-03-01T16:40:20Z"
          }
        ],
        "hostIP": "192.168.49.2",
        "podIP": "10.244.0.15",
        "podIPs": [
          {
            "ip": "10.244.0.15"
          }
        ],
        "startTime": "2023-03-01T16:40:20Z",
        "containerStatuses": [
          {
            "name": "nginx",
            "state": {
              "running": {
                "startedAt": "2023-04-20T16:52:25Z"
              }
            },
            "lastState": {
              "terminated": {
                "exitCode": 0,
                "reason": "Completed",
                "startedAt": "2023-04-20T09:03:51Z",
                "finishedAt": "2023-04-20T16:40:51Z",
                "containerID": "docker://9242fa924120abad4cc94016b73a92d00e63f2fb3e8fbda4f19f612bda23816e"
              }
            },
            "ready": true,
            "restartCount": 3,
            "image": "nginx:1.16",
            "imageID": "docker-pullable://nginx@sha256:d20aa6d1cae56fd17cd458f4807e0de462caf2336f0b70b5eeb69fcaaf30dd9c",
            "containerID": "docker://3e3c9b4b70065c80a8e898b5977788bae25ef6bbb2b406b1c87e238a56c3493b",
            "started": true
          }
        ],
        "qosClass": "BestEffort"
      }
    }
  ]
}
```

**Comment by hnaderi** [comment]
Just fixed the problem, you can use the snapshot version as soon as the CI publishes the artifacts, which is in about 20-30 minutes.
It was a problem with explicit nulls as optional empty, which apparently has different behavior between different k8s api servers.

**Comment by hnaderi** [comment]
You can use this to get the version with the fix, once it is published in a few minutes
```scala
ThisBuild / resolvers ++= Resolver.sonatypeOssRepos("snapshots")
libraryDependencies ++= Seq(
  "dev.hnaderi" %% "scala-k8s-http4s" % "0.10-76403e5-SNAPSHOT",
  "dev.hnaderi" %% "scala-k8s-circe" % "0.10-76403e5-SNAPSHOT"
)

**Comment by davesmith00sky** [comment]
Good morning @hnaderi, I've just tried the snapshot version and it appears to work perfectly! 😄 

Thanks for the quick turn around. 🙏

**Comment by hnaderi** [comment]
> Good morning @hnaderi, I've just tried the snapshot version and it appears to work perfectly! 😄 
> 
> Thanks for the quick turn around. 🙏 

Good to hear that, thank you for the bug report!
I'll drop a release soon.
Also let me know if you faced any problem.
